# Generated by Django 5.2 on 2025-06-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
